import { wazuhRuleRepoPath, type WazuhConditionOp } from "./constants";
import type { WazuhRuleCondition, WazuhRuleDefinition } from "./types";

/**
 * Renders the Wazuh XML for a rule. The rule is stored as structured fields and the file is always
 * generated from them, never accepted from a caller or from the AI: this function decides which
 * elements can ever appear (`if_group`/`if_sid`, `field`, `description`, `mitre`, `group`), so an
 * `active-response`, `command` or any other element is impossible by construction. Text is escaped
 * for XML, and a condition value is escaped for the regex it becomes before that.
 */

export function escapeXml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export function escapeRegex(text: string): string {
  return text.replace(/[\\^$.*+?()[\]{}|/-]/g, "\\$&");
}

/** The PCRE2 pattern a condition becomes. Always case-insensitive: Windows paths and switches vary in case. */
export function conditionPattern(op: WazuhConditionOp, value: string): string {
  if (op === "contains") return `(?i)${escapeRegex(value)}`;
  if (op === "equals") return `(?i)^${escapeRegex(value)}$`;
  return `(?i)${value}`;
}

function fieldLine(condition: WazuhRuleCondition): string {
  return `    <field name="${escapeXml(condition.field)}" type="pcre2">${escapeXml(
    conditionPattern(condition.op, condition.value),
  )}</field>`;
}

export function renderWazuhRuleXml(rule: WazuhRuleDefinition): string {
  // A repeating rule counts how often its parent matched, so it attaches with if_matched_*.
  const element =
    rule.frequency === null
      ? rule.parent_kind === "sid"
        ? "if_sid"
        : "if_group"
      : rule.parent_kind === "sid"
        ? "if_matched_sid"
        : "if_matched_group";
  const parent = `    <${element}>${escapeXml(rule.parent_value)}</${element}>`;
  const repeat =
    rule.frequency === null ? "" : ` frequency="${rule.frequency}" timeframe="${rule.timeframe}"`;
  const lines = [
    `<!-- ArcRadar rule ${rule.id}. Generated by ArcRadar: change it there, not in this file. -->`,
    `<group name="arcradar,">`,
    `  <rule id="${rule.id}" level="${rule.level}"${repeat}>`,
    parent,
    ...rule.same_fields.map((field) => `    <same_field>${escapeXml(field)}</same_field>`),
    ...rule.conditions.map(fieldLine),
    `    <description>${escapeXml(rule.name)}</description>`,
  ];
  if (rule.mitre_ids.length > 0) {
    lines.push(`    <mitre>`);
    for (const id of rule.mitre_ids) lines.push(`      <id>${escapeXml(id)}</id>`);
    lines.push(`    </mitre>`);
  }
  lines.push(`  </rule>`, `</group>`, ``);
  return lines.join("\n");
}

export { wazuhRuleRepoPath };
