import { describe, expect, it } from "vitest";
import { getDialect } from "@/lib/siem-rules/dialects";
import {
  assertSafeSplunkConf,
  buildSplunkSearch,
  splitPipeline,
  splQuote,
  splunkSpecSchema,
} from "@/lib/siem-rules/dialects/splunk";
import {
  aiSiemRuleSchema,
  createSiemRuleSchema,
  generateSiemRuleSchema,
  updateSiemRuleSchema,
} from "@/lib/siem-rules/schema";
import type { SiemRuleDefinition } from "@/lib/siem-rules/types";

const dialect = getDialect("splunk");

const spec = {
  index: "main",
  sourcetype: "WinEventLog:Security",
  conditions: [{ field: "EventCode", op: "equals" as const, value: "4625" }],
  threshold: { count: 5, window_minutes: 5, by: ["Source_Network_Address"] },
  schedule: "every_5_minutes" as const,
};

const rule = (overrides: Partial<SiemRuleDefinition> = {}): SiemRuleDefinition => ({
  rule_key: "1000",
  name: "Brute force from one address",
  description: null,
  severity: "high",
  mitre_ids: ["T1110"],
  spec: splunkSpecSchema.parse(spec),
  ...overrides,
});

describe("Splunk rule rendering", () => {
  it("renders one stanza from the fixed template", () => {
    const file = dialect.render(rule());
    expect(file.path).toBe("splunk/arcradar_1000.conf");
    expect(file.content).toBe(
      [
        "# ArcRadar rule 1000. Generated by ArcRadar: change it there, not in this file.",
        "[arcradar_1000]",
        "description = Brute force from one address",
        'search = index=main sourcetype=WinEventLog:Security | regex EventCode="(?i)^4625$" | stats count by Source_Network_Address | where count >= 5',
        "enableSched = 1",
        "cron_schedule = */5 * * * *",
        "dispatch.earliest_time = -5m",
        "dispatch.latest_time = now",
        "alert_type = number of events",
        "alert_comparator = greater than",
        "alert_threshold = 0",
        "alert.severity = 4",
        "alert.track = 1",
        "alert.digest_mode = 0",
        "alert.suppress = 1",
        "alert.suppress.period = 5m",
        "alert.suppress.fields = Source_Network_Address",
        "action.arcradar_forward = 1",
        "action.arcradar_forward.param.rule_key = 1000",
        "action.arcradar_forward.param.name = Brute force from one address",
        "action.arcradar_forward.param.severity = high",
        "action.arcradar_forward.param.mitre = T1110",
        "",
      ].join("\n"),
    );
  });

  it("renders a single-event rule without threshold, suppression or MITRE lines", () => {
    const file = dialect.render(
      rule({
        mitre_ids: [],
        spec: splunkSpecSchema.parse({ ...spec, threshold: null, schedule: "hourly" }),
      }),
    );
    expect(file.content).toContain("dispatch.earliest_time = -60m");
    expect(file.content).toContain("cron_schedule = 0 * * * *");
    expect(file.content).not.toContain("stats");
    expect(file.content).not.toContain("alert.suppress");
    expect(file.content).not.toContain(".param.mitre");
  });

  it("builds contains and regex conditions as escaped, quoted regexes", () => {
    const search = buildSplunkSearch(
      splunkSpecSchema.parse({
        index: "main",
        conditions: [
          { field: "CommandLine", op: "contains", value: "Set-MpPreference -Disable" },
          { field: "Image", op: "regex", value: "powershell\\.exe$".replace("$", "") },
        ],
      }),
    );
    expect(search).toBe(
      'index=main | regex CommandLine="(?i)Set\\\\-MpPreference \\\\-Disable" | regex Image="(?i)powershell\\\\.exe"',
    );
  });
});

describe("Splunk injection resistance", () => {
  const attacks = [
    '" | outputlookup evil.csv | search "',
    '"; | sendalert something',
    "x\n[evil_stanza]\nsearch = | delete",
    "a | script bad",
    "$result.host$",
    "tail\\",
    '"\\" | delete',
    "x\u0000y",
  ];

  for (const attack of attacks) {
    it(`never lets a value become SPL: ${JSON.stringify(attack)}`, () => {
      const parsed = splunkSpecSchema.safeParse({
        index: "main",
        conditions: [{ field: "CommandLine", op: "contains", value: attack }],
      });
      if (!parsed.success) return; // refused outright
      const { content } = dialect.render(rule({ spec: parsed.data, mitre_ids: [] }));
      const searchLine = content.split("\n").find((line) => line.startsWith("search = "));
      const [base, ...steps] = splitPipeline(searchLine!.slice("search = ".length));
      expect(base).toBe("index=main");
      expect(steps.map((segment) => segment.split(/\s+/, 1)[0])).toEqual(["regex"]);
      expect(content.match(/^\[/gm)).toHaveLength(1);
    });
  }

  it("refuses an index, sourcetype or field that is not a plain name", () => {
    const bad = (patch: object) =>
      splunkSpecSchema.safeParse({
        index: "main",
        conditions: [{ field: "EventCode", op: "equals", value: "1" }],
        ...patch,
      }).success;
    expect(bad({ index: "main | delete" })).toBe(false);
    expect(bad({ index: "*" })).toBe(false);
    expect(bad({ sourcetype: "x y" })).toBe(false);
    expect(bad({ sourcetype: "a|b" })).toBe(false);
    expect(bad({ conditions: [{ field: "a b", op: "equals", value: "1" }] })).toBe(false);
    expect(bad({ conditions: [{ field: "a|b", op: "equals", value: "1" }] })).toBe(false);
    expect(bad({ threshold: { count: 5, window_minutes: 5, by: ["x | delete"] } })).toBe(false);
  });

  it("refuses an unknown key in the spec", () => {
    expect(
      splunkSpecSchema.safeParse({
        index: "main",
        conditions: [{ field: "EventCode", op: "equals", value: "1" }],
        extra: "| delete",
      }).success,
    ).toBe(false);
  });

  it("refuses names that could break a .conf line", () => {
    const name = (text: string) =>
      createSiemRuleSchema(dialect).safeParse({
        name: text,
        severity: "high",
        spec,
      }).success;
    expect(name("ok name")).toBe(true);
    expect(name("trailing\\")).toBe(false);
    expect(name("two\nlines")).toBe(false);
    expect(name("token $x$")).toBe(false);
  });

  it("the renderer's own check rejects a tampered file", () => {
    const good = dialect.render(rule()).content;
    expect(() => assertSafeSplunkConf(good, "1000")).not.toThrow();
    expect(() =>
      assertSafeSplunkConf(good.replace("| where", "| outputlookup x.csv | where"), "1000"),
    ).toThrow(/outputlookup/);
    expect(() => assertSafeSplunkConf(good + "[other]\n", "1000")).toThrow();
    expect(() => assertSafeSplunkConf(good + "action.email = 1\n", "1000")).toThrow();
    expect(() => assertSafeSplunkConf(good, "9999")).toThrow();
    // a leading `search` command (it would search for the word), a subsearch, a free-form segment
    expect(() =>
      assertSafeSplunkConf(good.replace("search = index=", "search = search index="), "1000"),
    ).toThrow(/index=/);
    expect(() =>
      assertSafeSplunkConf(
        good.replace("search = index=main", "search = index=main [search index=x]"),
        "1000",
      ),
    ).toThrow(/index=/);
    expect(() =>
      assertSafeSplunkConf(
        good.replace("| where count >= 5", "| where count >= 5 | eval x=1"),
        "1000",
      ),
    ).toThrow(/eval/);
    expect(() =>
      assertSafeSplunkConf(good.replace("| stats count by", "| stats sum(x) by"), "1000"),
    ).toThrow(/stats/);
    expect(() =>
      assertSafeSplunkConf(good.replace("description = ", "description = a\\\n#"), "1000"),
    ).toThrow();
  });

  it("splits a pipeline only outside quoted strings", () => {
    expect(splitPipeline('search a="x | y" | regex f="a\\"|b" | stats count')).toEqual([
      'search a="x | y"',
      'regex f="a\\"|b"',
      "stats count",
    ]);
    expect(splQuote('a"b\\c')).toBe('"a\\"b\\\\c"');
  });
});

describe("spec rules", () => {
  it("needs a condition or a threshold", () => {
    expect(splunkSpecSchema.safeParse({ index: "main" }).success).toBe(false);
    expect(
      splunkSpecSchema.safeParse({
        index: "main",
        sourcetype: "WinEventLog:Security",
        threshold: { count: 5, window_minutes: 5, by: [] },
      }).success,
    ).toBe(true);
  });

  it("bounds the threshold and the number of conditions", () => {
    const t = (threshold: object) =>
      splunkSpecSchema.safeParse({
        index: "main",
        conditions: [{ field: "a", op: "equals", value: "1" }],
        threshold,
      }).success;
    expect(t({ count: 1, window_minutes: 5, by: [] })).toBe(false);
    expect(t({ count: 5, window_minutes: 0, by: [] })).toBe(false);
    expect(t({ count: 5, window_minutes: 1441, by: [] })).toBe(false);
    expect(t({ count: 5, window_minutes: 5, by: ["a", "b", "c", "d"] })).toBe(false);
    const many = Array.from({ length: 11 }, () => ({ field: "a", op: "equals", value: "1" }));
    expect(splunkSpecSchema.safeParse({ index: "main", conditions: many }).success).toBe(false);
  });

  it("applies the regex guard to a regex condition", () => {
    const regex = (value: string) =>
      splunkSpecSchema.safeParse({
        index: "main",
        conditions: [{ field: "a", op: "regex", value }],
      }).success;
    expect(regex("cmd\\.exe")).toBe(true);
    expect(regex("(a+)+")).toBe(false);
    expect(regex("(?=x)")).toBe(false);
  });

  it("the create, update and AI schemas share the checks", () => {
    const base = { name: "Rule", severity: "low", spec };
    expect(createSiemRuleSchema(dialect).safeParse(base).success).toBe(true);
    expect(createSiemRuleSchema(dialect).safeParse({ ...base, status: "pushed" }).success).toBe(
      false,
    );
    expect(createSiemRuleSchema(dialect).safeParse({ ...base, rule_key: "a b" }).success).toBe(
      false,
    );
    expect(aiSiemRuleSchema(dialect).safeParse({ ...base, severity: "urgent" }).success).toBe(
      false,
    );
    expect(updateSiemRuleSchema(dialect).safeParse({}).success).toBe(false);
    expect(updateSiemRuleSchema(dialect).safeParse({ rule_key: "x" }).success).toBe(false);
    expect(updateSiemRuleSchema(dialect).safeParse({ severity: "critical" }).success).toBe(true);
    expect(generateSiemRuleSchema.safeParse({ prompt: "short" }).success).toBe(false);
  });
});
