import { describe, expect, it, vi } from "vitest";
import type { ApiKeyPrincipal } from "@/lib/api-keys/types";
import {
  backtestBatchSchema,
  expectedSearchDigest,
  searchLineOf,
  sha256Hex,
} from "@/lib/siem-rules/backtest";

vi.mock("@/lib/siem-rules/backtest-repository", () => ({
  storeBacktests: vi.fn(),
  findBacktests: vi.fn(),
}));
vi.mock("@/lib/audit/write", () => ({ writeAuditLog: vi.fn() }));

const { ingestBacktests } = await import("@/lib/siem-rules/backtest-service");

const HASH = "a".repeat(64);

const result = (over: Record<string, unknown> = {}) => ({
  rule_key: "1000",
  window_hours: 24,
  kind: "threshold",
  matches: 3,
  scanned: 900,
  sample: [
    { time: "2026-10-06T10:00:00Z", count: 6, group: { Source_Network_Address: "203.0.113.5" } },
  ],
  search_sha256: HASH,
  ...over,
});

describe("backtestBatchSchema", () => {
  it("takes 1 to 200 results and nothing else", () => {
    expect(backtestBatchSchema.safeParse({ results: [result()] }).success).toBe(true);
    expect(backtestBatchSchema.safeParse({ results: [] }).success).toBe(false);
    expect(backtestBatchSchema.safeParse({ results: Array(201).fill(result()) }).success).toBe(
      false,
    );
    expect(backtestBatchSchema.safeParse({ results: [result()], extra: 1 }).success).toBe(false);
    expect(backtestBatchSchema.safeParse({ results: [result({ extra: 1 })] }).success).toBe(false);
  });

  it("only knows the two windows and the two kinds", () => {
    const bad = (over: Record<string, unknown>) =>
      backtestBatchSchema.safeParse({ results: [result(over)] }).success;
    expect(bad({ window_hours: 24 })).toBe(true);
    expect(bad({ window_hours: 168 })).toBe(true);
    expect(bad({ window_hours: 12 })).toBe(false);
    expect(bad({ kind: "events" })).toBe(true);
    expect(bad({ kind: "magic" })).toBe(false);
  });

  it("refuses a bad key, hash, count or sample", () => {
    const bad = (over: Record<string, unknown>) =>
      backtestBatchSchema.safeParse({ results: [result(over)] }).success;
    expect(bad({ rule_key: "a b" })).toBe(false);
    expect(bad({ rule_key: "x".repeat(61) })).toBe(false);
    expect(bad({ search_sha256: "nothex" })).toBe(false);
    expect(bad({ search_sha256: "A".repeat(64) })).toBe(false);
    expect(bad({ matches: -1 })).toBe(false);
    expect(bad({ matches: 1.5 })).toBe(false);
    expect(bad({ sample: Array(6).fill({ count: 1 }) })).toBe(false);
    expect(bad({ sample: [{ count: 1, extra: true }] })).toBe(false);
    expect(
      bad({ sample: [{ group: { a: "1", b: "2", c: "3", d: "4", e: "5", f: "6", g: "7" } }] }),
    ).toBe(false);
    expect(bad({ error: "x".repeat(301) })).toBe(false);
  });

  it("defaults the sample to none", () => {
    const parsed = backtestBatchSchema.parse({ results: [{ ...result(), sample: undefined }] });
    expect(parsed.results[0].sample).toEqual([]);
  });
});

describe("search digest", () => {
  const content = [
    "# ArcRadar rule 1000. Generated by ArcRadar.",
    "[arcradar_1000]",
    "description = x",
    'search = index=main | regex EventCode="(?i)^4625$"',
    "enableSched = 1",
    "",
  ].join("\n");

  it("is the SHA-256 of the search line's value, so a result for another search is recognizable", () => {
    expect(searchLineOf(content)).toBe('index=main | regex EventCode="(?i)^4625$"');
    expect(expectedSearchDigest(content)).toBe(
      sha256Hex('index=main | regex EventCode="(?i)^4625$"'),
    );
    expect(expectedSearchDigest(content.replace("4625", "4624"))).not.toBe(
      expectedSearchDigest(content),
    );
    expect(searchLineOf("[x]\n")).toBeNull();
    expect(expectedSearchDigest("[x]\n")).toBeNull();
  });

  it("does not depend on the mode of the rule", () => {
    expect(expectedSearchDigest(content.replace("enableSched = 1", "enableSched = 0"))).toBe(
      expectedSearchDigest(content),
    );
  });
});

describe("ingestBacktests", () => {
  it("stores the results and audits who sent how many, never what they found", async () => {
    const store = vi.fn().mockResolvedValue({ results: 2 });
    const audit = vi.fn().mockResolvedValue(true);
    const principal: ApiKeyPrincipal = {
      keyId: "0b8f4f3e-2f4e-4c55-9e0a-6a1a3a4b5c6d",
      keyName: "Splunk lab",
      keyPrefix: "arc_KKKK",
      ownerId: "3f0d3a86-5a53-4c8e-8f7e-1f2d3c4b5a69",
      scopes: ["ingest:splunk"],
    };
    const body = backtestBatchSchema.parse({
      results: [result(), result({ window_hours: 168 })],
    });
    const answer = await ingestBacktests(
      principal,
      "splunk",
      body,
      { headers: new Headers() },
      { store, audit },
    );
    expect(answer).toEqual({ results: 2 });
    expect(store).toHaveBeenCalledWith("splunk", body.results);
    const entry = JSON.stringify(audit.mock.calls[0][0]);
    expect(entry).toContain('"action":"ingest.backtest"');
    expect(entry).toContain('"results":2');
    expect(entry).not.toContain("203.0.113.5");
  });
});
