"use client";

import { GitBranch } from "lucide-react";
import { useRef, useState, type KeyboardEvent } from "react";
import { cn } from "@/lib/cn";

type RuleFile = { id: string; siem: string; path: string; lines: string[] };

/** What ArcRadar writes for the same idea ("five failed logons from one address") on each SIEM. */
const FILES: RuleFile[] = [
  {
    id: "splunk",
    siem: "Splunk",
    path: "splunk/arcradar_1001.conf",
    lines: [
      "# ArcRadar rule 1001. Generated by ArcRadar: change it there, not in this file.",
      "[arcradar_1001]",
      "description = Five failed logons from one address",
      'search = index=main sourcetype=WinEventLog:Security | regex EventCode="(?i)^4625$" | stats count by Source_Network_Address | where count >= 5',
      "enableSched = 1",
      "cron_schedule = */5 * * * *",
      "alert.suppress = 1",
      "alert.suppress.period = 5m",
      "action.arcradar_forward = 1",
      "action.arcradar_forward.param.severity = high",
      "action.arcradar_forward.param.mitre = T1110.001",
    ],
  },
  {
    id: "wazuh",
    siem: "Wazuh",
    path: "rules/arcradar_100241.xml",
    lines: [
      "<!-- ArcRadar rule 100241. Generated by ArcRadar: change it there, not in this file. -->",
      '<group name="arcradar,">',
      '  <rule id="100241" level="10" frequency="5" timeframe="300">',
      "    <if_matched_group>authentication_failed</if_matched_group>",
      "    <same_field>win.eventdata.ipAddress</same_field>",
      "    <description>Five failed logons from one address</description>",
      "    <mitre>",
      "      <id>T1110.001</id>",
      "    </mitre>",
      "  </rule>",
      "</group>",
    ],
  },
];

/** Colors one line: comments, the setting name of a `.conf` line, XML tags, quoted values. */
function CodeLine({ line }: { line: string }) {
  const trimmed = line.trimStart();
  if (trimmed.startsWith("#") || trimmed.startsWith("<!--")) {
    return <span className="text-muted">{line}</span>;
  }
  if (trimmed.startsWith("[")) return <span className="text-primary">{line}</span>;

  const setting = /^([\w.]+)( = )(.*)$/.exec(line);
  if (setting) {
    return (
      <>
        <span className="text-tone-blue-fg">{setting[1]}</span>
        <span className="text-muted">{setting[2]}</span>
        <span>{setting[3]}</span>
      </>
    );
  }

  const parts = line.split(/(<\/?[\w-]+|[\w-]+(?==")|"[^"]*"|\/?>)/g).filter(Boolean);
  return (
    <>
      {parts.map((part, index) => {
        let tone = "";
        if (/^<\/?[\w-]+$/.test(part) || part === ">" || part === "/>") tone = "text-tone-blue-fg";
        else if (/^[\w-]+$/.test(part) && line.includes(`${part}="`)) tone = "text-tone-amber-fg";
        else if (part.startsWith('"')) tone = "text-tone-green-fg";
        return (
          <span key={index} className={tone}>
            {part}
          </span>
        );
      })}
    </>
  );
}

/**
 * The same detection as the two files ArcRadar would commit, one tab per SIEM. Tabs follow the
 * usual keyboard pattern: arrow keys move between them, and only the selected one is a tab stop.
 */
export function RuleFiles() {
  const [selected, setSelected] = useState(0);
  const tabs = useRef<(HTMLButtonElement | null)[]>([]);
  const file = FILES[selected];

  function onKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    const step = event.key === "ArrowRight" ? 1 : event.key === "ArrowLeft" ? -1 : 0;
    if (step === 0) return;
    event.preventDefault();
    const next = (selected + step + FILES.length) % FILES.length;
    setSelected(next);
    tabs.current[next]?.focus();
  }

  return (
    <div className="overflow-hidden rounded-xl border border-border bg-surface">
      <div className="flex items-center justify-between gap-3 border-b border-border pr-4">
        <div
          role="tablist"
          aria-label="Rule file for each SIEM"
          onKeyDown={onKeyDown}
          className="flex"
        >
          {FILES.map((item, index) => (
            <button
              key={item.id}
              ref={(node) => {
                tabs.current[index] = node;
              }}
              type="button"
              role="tab"
              id={`rule-tab-${item.id}`}
              aria-selected={index === selected}
              aria-controls={`rule-panel-${item.id}`}
              tabIndex={index === selected ? 0 : -1}
              onClick={() => setSelected(index)}
              className={cn(
                "-mb-px border-b-2 px-4 py-3 text-sm font-medium transition-colors",
                index === selected
                  ? "border-primary text-foreground"
                  : "border-transparent text-muted hover:text-foreground",
              )}
            >
              {item.siem}
            </button>
          ))}
        </div>
        <span className="hidden min-w-0 items-center gap-2 font-mono text-xs text-muted sm:flex">
          <GitBranch aria-hidden className="size-3.5 shrink-0" />
          <span className="truncate">{file.path}</span>
        </span>
      </div>
      <div
        role="tabpanel"
        id={`rule-panel-${file.id}`}
        aria-labelledby={`rule-tab-${file.id}`}
        tabIndex={0}
        className="focus-visible:outline-2 focus-visible:-outline-offset-2"
      >
        <pre className="overflow-x-auto p-5">
          <code className="block text-[13px] leading-6">
            {file.lines.map((line, index) => (
              <span key={index} className="block pl-[2ch] -indent-[2ch] whitespace-pre-wrap">
                <CodeLine line={line} />
              </span>
            ))}
          </code>
        </pre>
      </div>
    </div>
  );
}
